source 'http://rubygems.org'
ruby "2.1.4"

gem 'rails', '4.1.0'

# Bundle edge Rails instead:
# gem 'rails', :git => 'git://github.com/rails/rails.git'

gem 'omniauth-twitter'
### gem 'sqlite3-ruby', :require => 'sqlite3'
gem 'gravatar_image_tag', '1.0.0.pre2'
gem 'redis'
gem 'twitter', '5.5.1'
gem 'will_paginate'


# Use unicorn as the web server
# gem 'unicorn'

# Deploy with Capistrano
# gem 'capistrano'

# To use debugger (ruby-debug for Ruby 1.8.7+, ruby-debug19 for Ruby 1.9.2+)
# gem 'ruby-debug'
# gem 'ruby-debug19'

# Bundle the extra gems:
# gem 'bj'
# gem 'nokogiri'
# gem 'sqlite3-ruby', :require => 'sqlite3'
# gem 'aws-s3', :require => 'aws/s3'


### group :assets do  TODO: remove assets group - rails 4 no longer needed
  gem 'sass-rails', "~> 4.0.0"
  gem 'coffee-rails', "~> 4.0.0"
  gem 'uglifier', '>= 1.3.0'
### end

gem 'jquery-rails'


# Bundle gems for the local environment. Make sure to
# put test-only gems in this group so their generators
# and rake tasks are available in development mode:
group :development do
  # gem 'webrat'
  # gem 'annotate-models', '1.0.4'
  gem 'faker'
  gem 'spring'
  gem 'sqlite3'
end

group :test do
  gem 'factory_girl_rails', '1.0'
  gem 'rspec-rails', '~> 2.14.0'
  gem 'rspec', '~> 2.14.0'
  gem 'sqlite3'
  gem 'webrat', '0.7.3'
end

group :production do
  gem "pg"
  gem "rails_12factor"
end

gem 'thin'


gem 'activerecord-session_store'


